### ISSUE TITLE
Project report download URL links to 404 Action not found

### ISSUE THREAD

**Issue by rhf104** [TAUSBV/dqf-api#103]
When requesting an annotation project report, the downloadUrl field links to
`"data-connector.taus.net/v3/project/{projectId}/report/download/json"` and results in a 404.

That resource doesn't appear in the documentation. However, the documented URL
`/v3/report/annotation/download/json/project/{projectId}` works fine. Maybe the inconsistency is a leftover from the older version of the api before requests were introduced?

**Comment by DavidKoot** [comment]
The 404 is correct. The resource cannot be found, because the url does not explain which type of report is requested, and is not formed according to the documentation.
Wrong:
`data-connector.taus.net/v3/project/{projectId}/report/download/json`
Correct:
`data-connector.taus.net/v3/report/annotation/download/json/project/{projectId}/`
`data-connector.taus.net/v3/report/correction/download/json/project/{projectId}/`
`data-connector.taus.net/v3/report/translation/download/json/project/{projectId}/`

So the setup of the url after report is:
1. the report type (annotation/correction/translation)
2. whether it is a request (this would be the first GET, that kicks of report generation), or a download
3. json format or not
4. project with the project id

**Comment by rhf104** [comment]
Thanks for the response. To clarify: I'm aware of how to successfully download a report; I wanted to file this issue because it didn't seem consistent that the URL provided in the response body from a report request isn't valid for downloading the requested report.

Example `GET /v3/report/annotation/request/project/{projectId}` response body:
```javascript
{
  "estimate": 0,
  "lastUpdated": 1533154863000,
  "downloadUrl": "data-connector.taus.net/v3/project/{projectId}/report/download"
}
```

Shouldn't `downloadUrl` be 
`data-connector.taus.net/v3/report/{reportType}/download/json/project/{projectId}/`?

**Comment by DavidKoot** [comment]
Point taken. This is a bug indeed. I changed the title of this issue. However, I need to copy the issue to another repository, which is private, and not accessible to you. Because the service that is taking care of these responses is not part of this repository. I will report to Spartan/Kevin though about the progress.
