### ISSUE TITLE
Enable multiple PMs from one company to see each other's projects

### ISSUE THREAD

**Issue by gorogattila** [TAUSBV/dqf-api#52]
Right now each PM has his/her PM key and they can't check each other's projects. A multi-user PM account could be created. Needs scoping out. Major change in DQF, API and Dashboard.

**Comment by achimr** [comment]
PMs belonging to the same company needs to be handled in the taus.net user database. Recreating this in DQF creates maintenance problem when PMs join/leave companies.

**Comment by pvalli** [comment]
@vinodMS again, more info for your scoping

**Comment by pvalli** [comment]
Adding on @achimr 's comments above I would ask the following questions: 

How do we handle the scenario of high turnaround within a company in the subscription model? 
What happens if a company buys an account for a PM who leaves before the end of the year? 
It actually applies to any level, not just PM.

Should we consider some kind of inheritance/transfer of data?
I would think via the primary user. What if the primary user changes?

**Comment by pvalli** [comment]
Feature Request - moved into Asana: https://app.asana.com/0/78315545221439/81343959392975
