### ISSUE TITLE
Adding the same translator multiple times should return the message "This translator is already added to the database".

### ISSUE THREAD

**Issue by gorogattila** [TAUSBV/dqf-api#57]
Adding the same translator multiple times should return the message "This translator exists already in  the database".

**Comment by achimr** [comment]
Currently the API returns the following response with HTTP status code 200 in the header and the following JSON response body:
{
  "code": 200,
  "type": "ok",
  "message": "The translator was succefully added to the database"
}

Instead we should return HTTP status code 409 Conflict
with a message "The translator with this email address already exists"
http://stackoverflow.com/questions/3825990/http-response-code-for-post-when-resource-already-exists

I think we should still send the email with the translator key to the translator email address. Otherwise the translator might never be able to retrieve a lost translator key.

**Comment by Impertatore** [comment]
I think that makes perfect sense; especially if the translator has lost the key and is performing that procedure for recovering the translator key again.

**Comment by pvalli** [comment]
This is a security/user management related point that has been moved to Asana: https://app.asana.com/0/78315545221439/81343959392943
