### ISSUE TITLE
DQF project creation API endpoint will not accept es-EM or es-XL as source languages

### ISSUE THREAD

**Issue by liemily** [TAUSBV/dqf-api#78]
The DQF project creation API endpoint will not accept es-EM (Spanish (International)) or es-XL (Spanish (Latin America)) as source languages.
These are two of the Spanish locales given from the new DQF language endpoint. However, these two are not valid Java locales. The locale.getISO3Country() method will return errors. I have checked, and this means that the project creation API endpoint will return an error if the source language is one of these two languages.

**Comment by nikosarg** [comment]
That's exactly the behaviour of the API because we validate the source language against the Java locales(locale.getISO3Country() method), as liemily has specified. 
We should first validate the given source language against our list of languages and if it doesn't exist in our database, we can validate it against the Java locales.

**Comment by nikosarg** [comment]
A solution has been implemented and can be tested on the [staging server] (http://dqf.ta-us.net/). It can be deployed on the production server with the v1.1 of the API.
