### ISSUE TITLE
Process on QD does not match options in Studio

### ISSUE THREAD

**Issue by pvalli** [TAUSBV/dqf-api#95]
on QD we have MT+PE+Human but this is not an option on the Studio plugin. Where does it come from and what does it mean?

![image](https://cloud.githubusercontent.com/assets/13329618/11431738/9623e078-949e-11e5-955b-e473cbdd0226.png)

![image](https://cloud.githubusercontent.com/assets/13329618/11431750/bf9e1f0e-949e-11e5-8a43-b41d0e58bf2b.png)

**Comment by HenkBoxma** [comment]
The DQF plugin gets the list with available options from the server and displays them. It seems that the API does not return this option.

**Comment by DavidKoot** [comment]
Henk, could you check the API call that gives you the result in the plugin and the looping over this result? I mean if it calls 
https://dqf.taus.net/api/v1/process/
you should get this JSON returned:
[{"id":5,"name":"Human","api_supported":1},{"id":2,"name":"MT+PE","api_supported":1},{"id":1,"name":"MT+PE+Human","api_supported":0},{"id":3,"name":"MT+PE+TM+Human","api_supported":1},{"id":4,"name":"TM+Human","api_supported":1}]

MT+PE+Human is the first according to the id.

**Comment by DavidKoot** [comment]
Sorry, misunderstandings all over the place. 
@HenkBoxma , the plugin somehow does what it should do. Although the option is available in the database, it is never an option that you would choose if you work in Trados Studio. So I guess, you deliberately removed the option at one point and forgot about it (other option: you made a mistake in your code that by accident gave the result that is actually exactly what we want). 
@pvalli , you and I decided that, because it is not a possible option in Trados Studio, it doesn't mean it has no place in the QD. Other visitors, for example coming from DQF tools, might be interested in this process filter. So we leave it like it is now. If Trados users are complaining that they find more processes in the QD than there are in Trados Studio, we might consider adding the process to the plugin, but only greyed out (which might raise the question how the option can be made available), or we should do some explaining on the QD why users can find more processes then their CATtool gives them.

**Comment by DavidKoot** [comment]
More info, I am quoting here my comment in https://github.com/TAUSBV/dqf-api/issues/49:
MT+PE+Human is a process that is really DQF tools only. It the 'experimental' design in which you can try and measure human translation (from scratch) against machine translation. From a multilingual file, half of the segments you have to post-edit, and the other half you need to translate. You then get to see the differences in number in the report.
There is no equivalent in any other translation tool. If there is any human translation needed in a file done by machine translation, then the process would still be called "MT+PE". 
So, in the API, this 'MT+PE+Human' is not returned, and therefore cannot be selected when you have to choose the process.
